language: python
python:
  - "3.5"
# Configure a headless display to test plot generation
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Install any dependencies for running the tests:
install: pip install codecov pytest-cov matplotlib jupyter git+https://github.com/computationalmodelling/nbval.git
# command to run tests
script:
  - py.test --cov=discretisedfield --cov-config .coveragerc
  - py.test --nbval docs/ipynb/*.ipynb
  - py.test --doctest-modules discretisedfield/*.py
after_success:
  codecov
notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF