environment:
  matrix:
    - PYTHON_VERSION: 3.8
      MINICONDA: C:\Miniconda38-x64

platform:
  - x64

build: false

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment
  - python -m pip install --upgrade pip nbval pycodestyle .

test_script:
  - python -c "import discretisedfield as df; import sys; sys.exit(df.test())"
  - python -m pytest -v --doctest-modules --ignore=discretisedfield\tests discretisedfield
  - python -m pytest -v --nbval docs\ipynb\
  - python -m pycodestyle --filename=*.py .
